### ISSUE TITLE
AC_LIB_LINKFLAGS_BODY(iconv) - syntax error

### ISSUE THREAD

**Issue by dimitardanailov** [gpoo/poppler#1]
Hi Everyone, 

If you try to install poppler with qt5 by follow command:

> ./configure --enable-poppler-qt5

I have this error:

> ./configure: line 23471: syntax error near unexpected token `iconv'
> ./configure: line 23471:`      AC_LIB_LINKFLAGS_BODY(iconv)'

I use Mac OS X version 10.9.4

Regards,
Dimitar

**Comment by gpoo** [comment]
Probably you want to grab `poppler` from the [official respository](http://poppler.freedesktop.org/). If the error still persists, please file a bug in [Poppler's Bugzilla](http://bugs.freedesktop.org/).

**Comment by toby20130333** [comment]
Yeah I have the same error ,what's workgroud here?
