### ISSUE TITLE
libpoppler-qt5 renderToImage()

### ISSUE THREAD

**Issue by narayanan-t2s** [gpoo/poppler#2]
Hello,

I'm trying to print a QImage created using libpoppler-qt5 renderToImage(). I'm facing issue with the font size while printing.

I'm displaying a html page in using QWebEngineView.  This html page contains text and image. I need to print this page with QPrinter with custom paper size.- ~ 71mmx73mm. I'm doing following steps before printing :

1) Converting the html contents to pdf using libpoppler's printTopdf().

2) Rendering the pdf pages into QImage using lbpoppler's renderToImage().

Issue I'm facing:

When I print the page using QPrinter, the font size of the rendered text (as I said before, the html page has both text and image)  is small, but the rendered image from html looks alright. 

Thanks,
Nara

**Comment by gpoo** [comment]
Hello.

This is my personal copy of the repository, but I am not a Poppler developer.

If you need assistance or want to report an issue, please refer to any of official Poppler channels. See https://poppler.freedesktop.org/ for information on how to reach each channel.
